### ISSUE TITLE
Invalid format when i put List

### ISSUE THREAD

**Issue by brunofrank** [thinreports/thinreports-generator#25]
To report works fine, but when i put a list i receive InvalidLayoutFormat.

Error:
```ruby
thinreports-0.8.0/lib/thinreports/core/format/builder.rb:14:in `rescue in build': Thinreports::Errors::InvalidLayoutFormat (Thinreports::Errors::InvalidLayoutFormat)
  from thinreports-0.8.0/lib/thinreports/core/format/builder.rb:10:in `build'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:41:in `block (3 levels) in build_internal'
  from thinreports-0.8.0/lib/thinreports/core/format/builder.rb:29:in `call'
  from thinreports-0.8.0/lib/thinreports/core/format/builder.rb:29:in `block in build_layout'
  from thinreports-0.8.0/lib/thinreports/core/format/builder.rb:28:in `scan'
  from thinreports-0.8.0/lib/thinreports/core/format/builder.rb:28:in `build_layout'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:40:in `block (2 levels) in build_internal'
  from thinreports-0.8.0/lib/thinreports/core/format/base.rb:60:in `call'
  from thinreports-0.8.0/lib/thinreports/core/format/base.rb:60:in `initialize'
  from thinreports-0.8.0/lib/thinreports/core/shape/manager/format.rb:13:in `initialize'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:39:in `new'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:39:in `block in build_internal'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:62:in `call'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:62:in `build_once'
  from thinreports-0.8.0/lib/thinreports/layout/format.rb:26:in `build_internal'
  from thinreports-0.8.0/lib/thinreports/core/format/builder.rb:10:in `build'
  from thinreports-0.8.0/lib/thinreports/layout/base.rb:22:in `load_format'
  from thinreports-0.8.0/lib/thinreports/layout/base.rb:39:in `initialize'
  from thinreports-0.8.0/lib/thinreports/layout.rb:8:in `new'
  from thinreports-0.8.0/lib/thinreports/layout.rb:8:in `new'
  from thinreports-0.8.0/lib/thinreports/report/internal.rb:133:in `init_layout'
  from thinreports-0.8.0/lib/thinreports/report/internal.rb:123:in `prepare_layout'
  from thinreports-0.8.0/lib/thinreports/report/internal.rb:22:in `initialize'
  from thinreports-0.8.0/lib/thinreports/report/base.rb:88:in `new'
  from thinreports-0.8.0/lib/thinreports/report/base.rb:88:in `initialize'
  from thinreports-0.8.0/lib/thinreports/report.rb:8:in `new'
  from thinreports-0.8.0/lib/thinreports/report.rb:8:in `new'
  from test.rb:5:in `<main>'
```

Gemfile
```ruby

source 'https://rubygems.org'


gem 'thinreports'
```

test.rb
```ruby
# coding: utf-8

require 'thinreports'

report = ThinReports::Report.new layout: 'exams_made.tlf'
report.start_new_page

report.generate(filename: 'hello_world.pdf')

puts 'Done!'
```

exams_made.tlf
```json

{"version":"0.8.0","config":{"title":"Exames efetuados","option":{},"page":{"paper-type":"A4","orientation":"portrait","margin-top":"20","margin-bottom":"20","margin-left":"20","margin-right":"20"}},"svg":"<svg width=\"595.2\" height=\"841.8\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" preserveAspectRatio=\"none\" viewBox=\"0 0 595.2 841.8\"><g class=\"canvas\"><g class=\"s-text\" stroke-width=\"0\" fill=\"#000000\" fill-opacity=\"1\" kerning=\"auto\" letter-spacing=\"normal\" x-display=\"true\" x-id=\"\" id=\"goog_486156199\" font-size=\"24\" font-family=\"Helvetica\" font-weight=\"normal\" font-style=\"normal\" text-anchor=\"middle\" text-decoration=\"none\" x-width=\"555.2\" x-height=\"24\" x-left=\"20\" x-top=\"116\"><rect class=\"s-text-box\" stroke=\"none\" fill=\"#000000\" fill-opacity=\"0.001\" width=\"555.2\" height=\"24\" x=\"20\" y=\"116\"/><text class=\"s-text-l0\" xml:space=\"preserve\" stroke=\"none\" fill=\"inherit\" fill-opacity=\"1\" text-decoration=\"none\" x=\"297.6\" y=\"134\">Exames laudados</text></g><!--SHAPE{\"type\":\"s-iblock\",\"id\":\"logo\",\"display\":\"true\",\"desc\":null,\"box\":{\"x\":20,\"y\":20,\"width\":173.2,\"height\":80},\"position-x\":\"left\",\"position-y\":\"top\",\"svg\":{\"tag\":\"image\",\"attrs\":{\"x\":20,\"y\":20,\"width\":173.2,\"height\":80}}}SHAPE--><!--LAYOUT<g xmlns=\"http://www.w3.org/2000/svg\" class=\"s-iblock\" x-display=\"true\" id=\"goog_532672952\" x-id=\"logo\" x-width=\"173.2\" x-height=\"80\" x-left=\"20\" x-top=\"20\" x-position-x=\"left\" x-position-y=\"top\"><rect class=\"s-iblock-box\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"0.2\" width=\"173.2\" height=\"80\" x=\"20\" y=\"20\"/><image xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"16\" height=\"16\" class=\"s-iblock-mark\" opacity=\"0.5\" xlink:href=\"assets/icons/x-image-mark.svg\" display=\"inline\" x=\"98\" y=\"52\"/><text class=\"s-iblock-id\" font-size=\"10.5\" font-family=\"Helvetica\" font-weight=\"normal\" font-style=\"normal\" text-decoration=\"none\" text-anchor=\"start\" kerning=\"auto\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"1\" x=\"24\" y=\"31\">logo</text></g>LAYOUT--><!--SHAPE{\"type\":\"s-list\",\"id\":\"exam_list\",\"display\":\"true\",\"desc\":null,\"footer\":{},\"footer-enabled\":\"false\",\"page-footer\":{},\"page-footer-enabled\":\"false\",\"detail\":{\"height\":26.3,\"svg\":{\"tag\":\"g\",\"content\":\"<!---SHAPE{\\\"type\\\":\\\"s-tblock\\\",\\\"id\\\":\\\"date\\\",\\\"display\\\":\\\"true\\\",\\\"desc\\\":null,\\\"multiple\\\":\\\"false\\\",\\\"valign\\\":\\\"\\\",\\\"line-height\\\":\\\"\\\",\\\"box\\\":{\\\"x\\\":20,\\\"y\\\":193.1,\\\"width\\\":193.2,\\\"height\\\":14},\\\"format\\\":{\\\"base\\\":\\\"#\\\",\\\"type\\\":\\\"datetime\\\",\\\"datetime\\\":{\\\"format\\\":\\\"\\\"}},\\\"value\\\":\\\"\\\",\\\"ref-id\\\":\\\"\\\",\\\"overflow\\\":\\\"\\\",\\\"word-wrap\\\":\\\"break-word\\\",\\\"svg\\\":{\\\"tag\\\":\\\"text\\\",\\\"attrs\\\":{\\\"x\\\":20,\\\"y\\\":204.1,\\\"xml:space\\\":\\\"preserve\\\",\\\"kerning\\\":\\\"auto\\\",\\\"letter-spacing\\\":\\\"normal\\\",\\\"id\\\":\\\"goog_532672956\\\",\\\"fill\\\":\\\"#000000\\\",\\\"fill-opacity\\\":\\\"1\\\",\\\"font-size\\\":\\\"14\\\",\\\"font-family\\\":\\\"Helvetica\\\",\\\"font-weight\\\":\\\"bold\\\",\\\"font-style\\\":\\\"normal\\\",\\\"text-anchor\\\":\\\"start\\\",\\\"text-decoration\\\":\\\"none\\\"}}}SHAPE---><!---SHAPE{\\\"type\\\":\\\"s-tblock\\\",\\\"id\\\":\\\"name\\\",\\\"display\\\":\\\"true\\\",\\\"desc\\\":null,\\\"multiple\\\":\\\"false\\\",\\\"valign\\\":\\\"\\\",\\\"line-height\\\":\\\"\\\",\\\"box\\\":{\\\"x\\\":220.2,\\\"y\\\":194,\\\"width\\\":355,\\\"height\\\":14},\\\"format\\\":{\\\"base\\\":\\\"\\\",\\\"type\\\":\\\"\\\"},\\\"value\\\":\\\"\\\",\\\"ref-id\\\":\\\"\\\",\\\"overflow\\\":\\\"\\\",\\\"word-wrap\\\":\\\"break-word\\\",\\\"svg\\\":{\\\"tag\\\":\\\"text\\\",\\\"attrs\\\":{\\\"x\\\":220.2,\\\"y\\\":205,\\\"xml:space\\\":\\\"preserve\\\",\\\"kerning\\\":\\\"auto\\\",\\\"letter-spacing\\\":\\\"normal\\\",\\\"id\\\":\\\"goog_532672957\\\",\\\"fill\\\":\\\"#000000\\\",\\\"fill-opacity\\\":\\\"1\\\",\\\"font-size\\\":\\\"14\\\",\\\"font-family\\\":\\\"Helvetica\\\",\\\"font-weight\\\":\\\"bold\\\",\\\"font-style\\\":\\\"normal\\\",\\\"text-anchor\\\":\\\"start\\\",\\\"text-decoration\\\":\\\"none\\\"}}}SHAPE--->\"},\"translate\":{\"x\":0,\"y\":-9.8}},\"header\":{\"height\":27,\"svg\":{\"tag\":\"g\",\"content\":\"<g xmlns=\\\"http://www.w3.org/2000/svg\\\" class=\\\"s-text\\\" stroke-width=\\\"0\\\" fill=\\\"#000000\\\" fill-opacity=\\\"1\\\" kerning=\\\"auto\\\" letter-spacing=\\\"normal\\\" x-display=\\\"true\\\" x-id=\\\"\\\" id=\\\"goog_532672954\\\" font-size=\\\"14\\\" font-family=\\\"Helvetica\\\" font-weight=\\\"bold\\\" font-style=\\\"normal\\\" text-anchor=\\\"middle\\\" text-decoration=\\\"none\\\" x-width=\\\"200\\\" x-height=\\\"14\\\" x-left=\\\"20\\\" x-top=\\\"152\\\"><rect class=\\\"s-text-box\\\" stroke=\\\"none\\\" fill=\\\"#000000\\\" fill-opacity=\\\"0.001\\\" width=\\\"200\\\" height=\\\"14\\\" x=\\\"20\\\" y=\\\"152\\\"/><text class=\\\"s-text-l0\\\" xml:space=\\\"preserve\\\" stroke=\\\"none\\\" fill=\\\"inherit\\\" fill-opacity=\\\"1\\\" text-decoration=\\\"none\\\" x=\\\"120\\\" y=\\\"163\\\">Data</text></g><g xmlns=\\\"http://www.w3.org/2000/svg\\\" class=\\\"s-text\\\" stroke-width=\\\"0\\\" fill=\\\"#000000\\\" fill-opacity=\\\"1\\\" kerning=\\\"auto\\\" letter-spacing=\\\"normal\\\" x-display=\\\"true\\\" x-id=\\\"\\\" id=\\\"goog_532672955\\\" font-size=\\\"14\\\" font-family=\\\"Helvetica\\\" font-weight=\\\"bold\\\" font-style=\\\"normal\\\" text-anchor=\\\"middle\\\" text-decoration=\\\"none\\\" x-width=\\\"350\\\" x-height=\\\"14\\\" x-left=\\\"225.2\\\" x-top=\\\"152\\\"><rect class=\\\"s-text-box\\\" stroke=\\\"none\\\" fill=\\\"#000000\\\" fill-opacity=\\\"0.001\\\" width=\\\"350\\\" height=\\\"14\\\" x=\\\"225.2\\\" y=\\\"152\\\"/><text class=\\\"s-text-l0\\\" xml:space=\\\"preserve\\\" stroke=\\\"none\\\" fill=\\\"inherit\\\" fill-opacity=\\\"1\\\" text-decoration=\\\"none\\\" x=\\\"400.2\\\" y=\\\"163\\\">Exame</text></g>\"},\"translate\":{\"x\":0,\"y\":3}},\"header-enabled\":\"true\",\"svg\":{\"tag\":\"g\",\"attrs\":{}},\"content-height\":172.1,\"page-break\":\"true\"}SHAPE--><!--LAYOUT<g xmlns=\"http://www.w3.org/2000/svg\" class=\"s-list\" x-id=\"exam_list\" x-header-enabled=\"true\" x-page-footer-enabled=\"false\" x-footer-enabled=\"false\" x-changing-page=\"true\" x-display=\"true\" id=\"goog_532672953\" width=\"555.2\" height=\"199.1\" x=\"20\" y=\"150\"><g class=\"s-list-header\" transform=\"translate(0,3) rotate(0 0 0)\" x-top=\"150\" x-height=\"27\"><g class=\"s-text\" stroke-width=\"0\" fill=\"#000000\" fill-opacity=\"1\" kerning=\"auto\" letter-spacing=\"normal\" x-display=\"true\" x-id=\"\" id=\"goog_532672954\" font-size=\"14\" font-family=\"Helvetica\" font-weight=\"bold\" font-style=\"normal\" text-anchor=\"middle\" text-decoration=\"none\" x-width=\"200\" x-height=\"14\" x-left=\"20\" x-top=\"152\"><rect class=\"s-text-box\" stroke=\"none\" fill=\"#000000\" fill-opacity=\"0.001\" width=\"200\" height=\"14\" x=\"20\" y=\"152\"/><text class=\"s-text-l0\" xml:space=\"preserve\" stroke=\"none\" fill=\"inherit\" fill-opacity=\"1\" text-decoration=\"none\" x=\"120\" y=\"163\">Data</text></g><g class=\"s-text\" stroke-width=\"0\" fill=\"#000000\" fill-opacity=\"1\" kerning=\"auto\" letter-spacing=\"normal\" x-display=\"true\" x-id=\"\" id=\"goog_532672955\" font-size=\"14\" font-family=\"Helvetica\" font-weight=\"bold\" font-style=\"normal\" text-anchor=\"middle\" text-decoration=\"none\" x-width=\"350\" x-height=\"14\" x-left=\"225.2\" x-top=\"152\"><rect class=\"s-text-box\" stroke=\"none\" fill=\"#000000\" fill-opacity=\"0.001\" width=\"350\" height=\"14\" x=\"225.2\" y=\"152\"/><text class=\"s-text-l0\" xml:space=\"preserve\" stroke=\"none\" fill=\"inherit\" fill-opacity=\"1\" text-decoration=\"none\" x=\"400.2\" y=\"163\">Exame</text></g></g><g class=\"s-list-detail\" transform=\"translate(0,-9.8) rotate(0 0 0)\" x-top=\"177\" x-height=\"26.3\"><g class=\"s-tblock\" x-format-type=\"datetime\" x-value=\"\" x-format-base=\"#\" x-ref-id=\"\" kerning=\"auto\" letter-spacing=\"normal\" x-display=\"true\" x-multiple=\"false\" id=\"goog_532672956\" x-id=\"date\" fill=\"#000000\" fill-opacity=\"1\" font-size=\"14\" font-family=\"Helvetica\" font-weight=\"bold\" font-style=\"normal\" text-anchor=\"start\" text-decoration=\"none\" x-width=\"193.2\" x-height=\"14\" x-left=\"20\" x-top=\"193.1\" x-format-datetime-format=\"\"><rect class=\"s-tblock-box\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"0.2\" width=\"193.2\" height=\"14\" x=\"20\" y=\"193.1\"/><text class=\"s-tblock-id\" font-size=\"10.5\" font-family=\"Helvetica\" font-weight=\"normal\" font-style=\"normal\" text-decoration=\"none\" text-anchor=\"start\" kerning=\"auto\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"1\" x=\"24\" y=\"204.1\">date</text></g><g class=\"s-tblock\" x-format-type=\"\" x-value=\"\" x-format-base=\"\" x-ref-id=\"\" kerning=\"auto\" letter-spacing=\"normal\" x-display=\"true\" x-multiple=\"false\" id=\"goog_532672957\" x-id=\"name\" fill=\"#000000\" fill-opacity=\"1\" font-size=\"14\" font-family=\"Helvetica\" font-weight=\"bold\" font-style=\"normal\" text-anchor=\"start\" text-decoration=\"none\" x-width=\"355\" x-height=\"14\" x-left=\"220.2\" x-top=\"194\"><rect class=\"s-tblock-box\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"0.2\" width=\"355\" height=\"14\" x=\"220.2\" y=\"194\"/><text class=\"s-tblock-id\" font-size=\"10.5\" font-family=\"Helvetica\" font-weight=\"normal\" font-style=\"normal\" text-decoration=\"none\" text-anchor=\"start\" kerning=\"auto\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"1\" x=\"224.2\" y=\"205\">name</text></g></g><g class=\"s-list-page-footer\" transform=\"translate(0,-23.3) rotate(0 0 0)\" x-top=\"203.3\" x-height=\"0\" display=\"none\"/><g class=\"s-list-footer\" transform=\"translate(0,-53.2) rotate(0 0 0)\" x-top=\"203.3\" x-height=\"0\" display=\"none\"/><text class=\"s-list-id\" font-size=\"10\" font-family=\"Helvetica\" font-weight=\"normal\" font-style=\"normal\" text-anchor=\"start\" stroke=\"none\" fill=\"#0096fd\" fill-opacity=\"1\" x=\"24\" y=\"162\">exam_list</text><rect stroke-dasharray=\"2\" stroke=\"#0096fd\" stroke-width=\"0.5\" fill=\"#FFFFFF\" fill-opacity=\"0\" class=\"s-list-face\" width=\"555.2\" height=\"199.1\" x=\"20\" y=\"150\"/></g>LAYOUT--></g></svg>","state":{"layout-guide":[]}}
```

**Comment by hidakatsuya** [comment]
@brunofrank Thank you for your reporting. I'll confirm the issue.

**Comment by hidakatsuya** [comment]
@brunofrank Can you tell me version of Ruby you are using?

**Comment by brunofrank** [comment]
ruby 2.2.0preview1 (2014-09-17 trunk 47616) [x86_64-darwin14]

**Comment by brunofrank** [comment]
Sorry man, I did not realize that i was using a preview version, i update to 2.2.1 and report works like a charm. 

Thank you for attention.
