### ISSUE TITLE
Image item from base 64

### ISSUE THREAD

**Issue by manolo07** [thinreports/thinreports-generator#38]
Hi guys!
Firstable I want to thank you for this great job, and this more than an issue its a question.
I wanto to knwo if there´s al ready a way to setup an image item from a base64  or other (it may in memory) besides read it from file system?

Thank you for your help

**Comment by maeda-m** [comment]
Hi, @manolo07

There is a way to embed the Base64 images to PDF.
This Try refer to: https://github.com/thinreports/thinreports-examples/blob/master/image-block/image_block.rb#L16

Hope that helps.

**Comment by manolo07** [comment]
Thanks @maeda-m I just check it out and got this error:
```
/Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/document/graphics/image.rb:72:in `extname': no implicit conversion of StringIO into String (TypeError)
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/document/graphics/image.rb:72:in `normalize_image_from_file'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/document/graphics/image.rb:42:in `image_box'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/document/draw_shape.rb:45:in `draw_shape_iblock'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/drawer/page.rb:68:in `draw_iblock_shape'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/drawer/page.rb:40:in `draw_shape'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/drawer/page.rb:26:in `block in draw'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/drawer/page.rb:17:in `each_key'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/drawer/page.rb:17:in `draw'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf.rb:48:in `draw_page'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf.rb:38:in `block in draw_report'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf.rb:37:in `each'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf.rb:37:in `draw_report'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf.rb:30:in `generate'
	from /Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/report/base.rb:185:in `generate'
	from image_block.rb:22:in `<main>'
```
Later I tried:
```ruby
base64_image = StringIO.new(Base64.decode64(red_dot))
page.item(:base64_image).value(base64_image.read)
```
and got:
```
/Users/Manolo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/document/graphics/image.rb:72:in `extname': string contains null byte (ArgumentError)
```

I'm using ruby 2.2.3 with rails Rails 4.2.4 and thinreports (0.8.1) gem

**Comment by maeda-m** [comment]
@manolo07 Thank you for reporting! 

I have encountered the same issue.

However, it seems to be just a matter of thinreports 0.8.1.
Because, I was able to generate a successful PDF in 0.8.0.

*v0.8.0*

```
$ cd thinreports-examples/image-block/
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Installing pdf-core 0.4.0
Installing ttfunk 1.4.0
Installing prawn 1.3.0
Installing thinreports 0.8.0
Using bundler 1.10.6
Bundle complete! 1 Gemfile dependency, 5 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from prawn:
$ bundle exec ruby image_block.rb 
#=> generate a successful PDF
```

*v0.8.1*

```
$ bundle update
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using chunky_png 1.3.5
Using pdf-core 0.4.0
Using ttfunk 1.4.0
Using prawn 1.3.0
Using thinreports 0.8.1 (was 0.8.0)
Using bundler 1.10.6
Bundle updated!

$ bundle exec ruby image_block.rb 
/Users/maeda/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thinreports-0.8.1/lib/thinreports/generator/pdf/document/graphics/image.rb:72:in `extname': no implicit conversion of StringIO into String (TypeError)
```

**Comment by manolo07** [comment]
Correct, it works fine on 0.8.0, thank you!
