### ISSUE TITLE
TLF of 0.8.2 does not work in the Generator of 0.9.0

### ISSUE THREAD

**Issue by maeda-m** [thinreports/thinreports-generator#66]
https://github.com/thinreports/thinreports-examples/tree/0.8/estimate

0.8.2 のEditor で作成された TLF(estimate.tlf) を0.9.0 のGeneratorで使用すると以下のエラーになる。
```
$ ruby estimate.rb
[DEPRECATION] Support for the layout file with old format that generated with Editor 0.8 or lower will be dropped in Thinreports 1.1. Please convert to new layout format using Thinreports Editor 0.9 or 1.0.
xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/manager/target.rb:34:in `item': The layout does not have a Basic Item with id 'no'. (Thinreports::Errors::UnknownItemId)
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/manager/target.rb:69:in `block in values'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/manager/target.rb:69:in `each'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/manager/target.rb:69:in `values'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/list/manager.rb:123:in `build_section'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/list/manager.rb:103:in `insert_detail'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/list/manager.rb:93:in `add_detail'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/list/page.rb:52:in `add_row'
        from estimate.rb:109:in `block (3 levels) in <main>'
        from estimate.rb:107:in `each'
        from estimate.rb:107:in `block (2 levels) in <main>'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/utils.rb:32:in `call'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/utils.rb:32:in `call_block_in'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/core/shape/manager/target.rb:94:in `list'
        from estimate.rb:89:in `block in <main>'
        from estimate.rb:73:in `each'
        from estimate.rb:73:in `<main>'
```

**Comment by maeda-m** [comment]
Tried in other Ruby version was the same error message.

* ruby 2.0.0p247
```
>bundle show
Gems included by the bundle:
  * bundler (1.3.5)
  * chunky_png (1.3.5)
  * pdf-core (0.4.0)
  * prawn (1.3.0)
  * thinreports (0.9.0)
  * ttfunk (1.4.0)
```
* ruby 2.1.5p273
```
>bundle show
Gems included by the bundle:
  * bundler (1.9.4)
  * chunky_png (1.3.5)
  * pdf-core (0.4.0)
  * prawn (1.3.0)
  * thinreports (0.9.0)
  * ttfunk (1.4.0)
```
* ruby 2.2.3p173
```
>bundle show
Gems included by the bundle:
  * bundler (1.10.6)
  * chunky_png (1.3.5)
  * pdf-core (0.4.0)
  * prawn (1.3.0)
  * thinreports (0.9.0)
  * ttfunk (1.4.0)
```

**Comment by maeda-m** [comment]
### OK

* https://github.com/thinreports/thinreports-examples/tree/0.8/eudc
* https://github.com/thinreports/thinreports-examples/tree/0.8/event
* https://github.com/thinreports/thinreports-examples/tree/0.8/image-block
* https://github.com/thinreports/thinreports-examples/tree/0.8/text-block

### NG(Same error messages)

* https://github.com/thinreports/thinreports-examples/tree/0.8/list/advanced

### NG(New error messages)

```
[DEPRECATION] Support for the layout file with old format that generated with Editor 0.8 or lower will be dropped in Thinreports 1.1. Please convert to new layout format using Thinreports Editor 0.9 or 1.0.
xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/layout/legacy_schema.rb:259:in `list_section_schema': undefined method `[]' for nil:NilClass (NoMethodError)
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/layout/legacy_schema.rb:251:in `list_item_schema'
        from xxx/ruby/215-p0/lib/ruby/gems/2.1.0/gems/thinreports-0.9.0/lib/thinreports/layout/legacy_schema.rb:53:in `block in build_item_schemas_from_svg'
```

* https://github.com/thinreports/thinreports-examples/tree/0.8/list/basic
* https://github.com/thinreports/thinreports-examples/tree/0.8/list/group-rows

**Comment by maeda-m** [comment]
Reference ID could not have been applied. Other behavior is OK.
![estimate-ja-diff](https://cloud.githubusercontent.com/assets/943541/15767600/54e1a642-2984-11e6-8926-16ac6d321546.png)
